# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e2e2d883-d1d7-4df1-a4e2-748c3c4d2345";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-13bcf084-d4c7-43f9-ad09-284ae1378dcc".device =
    "/dev/disk/by-uuid/13bcf084-d4c7-43f9-ad09-284ae1378dcc";

  fileSystems."/home/${config.username}" = {
    device = "/dev/disk/by-uuid/eb68cffd-aa1d-43ab-a0bd-06c3f30dd98a";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-f16b06fd-b6c1-408d-bcc3-8569179443f2".device =
    "/dev/disk/by-uuid/f16b06fd-b6c1-408d-bcc3-8569179443f2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8D0A-5DE5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
