wallpaper {
    monitor = eDP-1
    path = /home/roberto/dotfiles/themer/theme-one/themer-wallpaper-block-wave/themer-wallpaper-block-wave-dark-2880x1800.png
}

wallpaper {
    monitor = DP-2
    path = /home/roberto/dotfiles/themer/theme-one/themer-wallpaper-block-wave/themer-wallpaper-block-wave-dark-2880x1800.png
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/roberto/dotfiles/themer/theme-one/themer-wallpaper-block-wave/themer-wallpaper-block-wave-dark-2880x1800.png
}

splash = false
