#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#    if [ -d /etc/X11/xinit/xinitrc.d ]; then
	#    for f in /etc/X11/xinit/xinitrc.d/*; do
		#    [ -x "$f" ] && . "$f"
	#    done
	#    unset f
#    fi
#
#exec openbox-session
#exec xmodmap ~/.speedswapper
#exec gnome-session
# exec startkde
# exec startxfce4

#exec fusion-icon

session=${1:-i3}

case $session in
	compiz)
		# Unlock gnome-keyring
		eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
		export SSH_AUTH_SOCK
		# Run compiz as standalone WM
		( sleep 0s && exec touchegg ) &
		( sleep 0s && exec xfce4-panel ) &
		( sleep 0s && exec sh ~/.fehbg ) &
		#( sleep 5s && exec mate-volume-control-applet ) &
		( sleep 3s && exec volumeicon ) &
		( sleep 5s && exec nm-applet ) &
		( sleep 8s && exec albert ) &
		( sleep 8s && exec xfce4-power-manager ) &
		#( sleep 10s && exec synapse --startup ) &
		#( sleep 20s && exec dropbox ) &
		#( sleep 20s && exec megasync ) &
		( sleep 20s && exec thunar --daemon ) &
		( sleep 30s && exec xscreensaver -nosplash ) &
		exec fusion-icon # compiz manager
		;;
	i3)
    # Set key repeat
    xset r rate 200 35
    # xmodmap ~/.speedswapper
    # Load default monitor layout
    $HOME/.screenlayout/default.sh
    # Enable UIM as input method
    # export GTK_IM_MODULE='uim'
    # export QT_IM_MODULE='uim'
    # uim-xim &
    # export XMODIFIERS='@im=uim'
    # Unlock gnome-keyring
    dbus-update-activation-environment --systemd DISPLAY
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
		export SSH_AUTH_SOCK
    # Enable gnome authentication agent
		exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    # Run i3 window manager
		exec i3
		;;
	steam)
		exec steam -bigpicture
		;;
	kde)
		exec startkde
		;;
	term)
		exec terminator -mb
		;;
	*) exec $1
esac

#exec stremio

# ...or the Window Manager of your choice
