hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -- nm-applet")
  hl.exec_cmd("uwsm app -- keepassxc")
  hl.exec_cmd("uwsm app -- owncloud")
  hl.exec_cmd("uwsm app -- hyprpaper -c ~/.config/hypr/hyprpaper.conf")
  hl.exec_cmd("uwsm app -- hypridle -c ~/.config/hypr/hypridle.conf")
  hl.exec_cmd("uwsm app -- waybar")
  hl.exec_cmd("uwsm app -- volumeicon")
  hl.exec_cmd("eval $(ssh-agent) &")
  hl.exec_cmd("hyprpm reload -nn")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME SSH_AUTH_SOCK")
end)
